// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUCBYz0h16Cts3SVojm5B_ryRYHR_76Mo',
    appId: '1:863675084155:android:14e7626d077360ee04a1de',
    messagingSenderId: '863675084155',
    projectId: 'chatify-c485c',
    storageBucket: 'chatify-c485c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1kq3qqpwtR-1ijLW6qyXnKM7Ci5r1y3o',
    appId: '1:863675084155:ios:2902628747fb5b9b04a1de',
    messagingSenderId: '863675084155',
    projectId: 'chatify-c485c',
    storageBucket: 'chatify-c485c.firebasestorage.app',
    androidClientId:
        '863675084155-hoqj8mrmtdt2v2f4umm5n3b8vv8bndr3.apps.googleusercontent.com',
    iosClientId:
        '863675084155-244b5a9joc37mp424c0mvjnbjv1mlock.apps.googleusercontent.com',
    iosBundleId: 'com.ajmal.threadsApp',
  );
}
